[package]
name = "qiqss-slides-typst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Yannick Lapointe <@yalap13>"]
license = "MIT"
description = "A presentation slides template for the QIQSS research group at Universit√© de Sherbrooke."
repository = "https://github.com/yalap13/qiqss-slides-typst.git"

[template]
path = "template"
entrypoint = "main.typ"
